routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::controller(App\Http\Controllers\PagesController::class)
    ->as('page.')
    ->group(function () {
        Route::get('/', 'index')->name('home');
        Route::get('/about', 'about')->name('about');
        Route::get('/contact', 'contact')->name('contact');
        Route::get('/ulasan/{jenisUlasan}', 'ulasan')->name('ulasan');
        Route::post('/ulasan/{jenisUlasan}', 'ulasanPost')->name('ulasan.post');
    });

Route::controller(App\Http\Controllers\MenuController::class)
    ->as('menu.')
    ->prefix('menu')
    ->group(function () {
        Route::get('/', 'menu')->name('menu');
        Route::get('/pengunjung', 'pengunjung')->name('pengunjung');
        Route::get('/forms/pengunjung', 'pengunjung')->name('forms.pengunjung');
        Route::get('/peminjaman', 'peminjaman')->name('peminjaman');
    });


Route::controller(App\Http\Controllers\Service\AuthController::class)->prefix('auth')->group(function () {
    Route::get('login', 'loginPage')->middleware('guest')->name('login');
    Route::post('login', 'loginPost')->middleware('guest')->name('login.post');
    Route::post('logout', 'logout')->middleware('auth')->name('logout');
});
Route::middleware('auth')->prefix('admin')->as('admin.')->group(function () {
    Route::controller(App\Http\Controllers\Admin\PageController::class)->group(function () {
        Route::get('/', 'index')->name('dashboard');
    });
    Route::resource('lending', App\Http\Controllers\Admin\LendingController::class);
    Route::resource('guest', App\Http\Controllers\Admin\GuestController::class);
    Route::resource('items', App\Http\Controllers\Admin\ItemsController::class);

    Route::controller(App\Http\Controllers\ExportController::class)->group(function () {
        Route::get('/export/datatamu', 'exportDataTamu')->name('export.datatamu');
        Route::get('/export/datapeminjaman', 'exportDataPeminjaman')->name('export.peminjaman');
    });
});

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function lending()
    {
        return $this->hasMany(FormLending::class, 'item_id');
    }
}

app/Http/Controllers/Admin/ItemsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Item;
use Illuminate\Http\Request;

class ItemsController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        return view('admin.items.index', [
            'barang' => Item::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('admin.items.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'nama_barang' => 'required',
        ]);

        Item::create($request->post());

        return redirect()->route('admin.items.index')->with('success', 'Data Barang berhasil disimpan');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
        $barang = Item::find($id);

        if (\is_null($barang)) {
            return redirect()->back()->with('error', 'Data Barang tidak terdaftar');
        }

        return view('admin.items.show', \compact('barang'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
        return redirect()->route('admin.items.show', ['item' => $id]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
        $barang = Item::find($id);

        $request->validate([
            'nama_barang' => 'required',
        ]);

        if (\is_null($barang)) {
            return redirect()->back()->with('error', 'Data Barang tidak terdaftar');
        }

        $barang->nama_barang = $request->post('nama_barang');
        $barang->penginput = auth()->user()->name;

        $barang->save();

        return redirect()->route('admin.items.index')->with('success', 'Data Barang berhasil di audit.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
        Item::destroy($id);
        return redirect()->route('admin.items.index')->with('success', 'Data Barang berhasil dihapus');
    }
}

resources/views/admin/items/create.blade.php
@extends('layouts.admin')

@section('title', 'Form Tambah Data Fasillitas')

@section('content')
    <div class="card card-body shadow">
        <legend class="text-primary mb-3">Form Tambah Data Fasillitas</legend>
        <form action="{{ route('admin.items.store') }}" method="post">
            @csrf
            <input type="hidden" value="{{ auth()->user()->name }}" name="penginput">
            <div class="row mb-3">
                <div class="col-lg-4 mb-sm-3 mb-lg-0">
                    <label for="nama_barang">Nama Fasillitas</label>
                </div>
                <div class="col-lg">
                    <input type="text" name="nama_barang" id="nama_barang" class="form-control" placeholder="Ruang Aula"
                        required>
                </div>
            </div>
            <input type="hidden" name="kuantitas" value="1">
            <hr />
            <div class="row">
                <div class="col">
                    <a href="{{ route('admin.items.index') }}" class="btn btn-outline-secondary w-100">
                        Kembali
                    </a>
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary w-100">
                        Simpan
                    </button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/items/edit.blade.php
@extends('layouts.admin')

@section('title', 'Form Audit Data Barang')

@section('content')
    <div class="card card-body shadow">
        <h3 class="text-primary">Form Audit Data Barang</h3>
    </div>
@endsection

resources/views/admin/items/index.blade.php
@extends('layouts.admin')

@section('title', 'Daftar Fasillitas')

@section('content')
    <div class="card card-body shadow">
        <h3 class="text-primary mb-3">Daftar Fasillitas</h3>
        <div class="text-end mb-3">
            <a href="{{ route('admin.items.create') }}" class="btn btn-primary">
                <em class="bi bi-plus"></em> Tambah Fasillitas
            </a>
        </div>
        @include('alerts')
        <div class="table-responsive">
            <table class="table table-striped table-hovered" id="table">
                <thead>
                    <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Nama Fasillitas</th>
                        <th scope="col">Penginput</th>
                        <th scope="col">Tanggal Dibuat</th>
                        <th scope="col">Opsi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($barang as $b)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $b->nama_barang }}</td>
                            <td>{{ $b->penginput }}</td>
                            <td>{{ $b->created_at }}</td>
                            <td class="d-flex">
                                <a href="{{ route('admin.items.show', ['item' => $b->id]) }}"
                                    class="btn btn-sm btn-outline-info me-1">
                                    <em class="bi bi-eye"></em>
                                </a>
                                <form action="{{ route('admin.items.destroy', ['item' => $b->id]) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-outline-danger">
                                        <em class="bi bi-trash"></em>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/admin/items/show.blade.php
@extends('layouts.admin')

@section('title', 'Detail Barang')

@section('content')
    <div class="card card-body shadow">
        <h3 class="text-primary">Detail Fasilitas</h3>

        <form action="{{ route('admin.items.update', ['item' => $barang->id]) }}" method="post">
            @csrf
            @method('PUT')
            <div class="row mb-3">
                <div class="col-lg-4 mb-sm-3 mb-lg-0">
                    <label for="nama_barang">Nama Fasilitas</label>
                </div>
                <div class="col-lg">
                    <input type="text" name="nama_barang" id="nama_barang" value="{{ $barang->nama_barang }}"
                        class="form-control" placeholder="Sapu" required>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <a href="{{ route('admin.items.index') }}" class="btn btn-outline-secondary w-100">
                        Kembali
                    </a>
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary w-100">
                        Simpan
                    </button>
                </div>
            </div>
        </form>
    </div>
@endsection