routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::controller(App\Http\Controllers\PagesController::class)
    ->as('page.')
    ->group(function () {
        Route::get('/', 'index')->name('home');
        Route::get('/about', 'about')->name('about');
        Route::get('/contact', 'contact')->name('contact');
        Route::get('/ulasan/{jenisUlasan}', 'ulasan')->name('ulasan');
        Route::post('/ulasan/{jenisUlasan}', 'ulasanPost')->name('ulasan.post');
    });

Route::controller(App\Http\Controllers\MenuController::class)
    ->as('menu.')
    ->prefix('menu')
    ->group(function () {
        Route::get('/', 'menu')->name('menu');
        Route::get('/pengunjung', 'pengunjung')->name('pengunjung');
        Route::get('/forms/pengunjung', 'pengunjung')->name('forms.pengunjung');
        Route::get('/peminjaman', 'peminjaman')->name('peminjaman');
    });


Route::controller(App\Http\Controllers\Service\AuthController::class)->prefix('auth')->group(function () {
    Route::get('login', 'loginPage')->middleware('guest')->name('login');
    Route::post('login', 'loginPost')->middleware('guest')->name('login.post');
    Route::post('logout', 'logout')->middleware('auth')->name('logout');
});
Route::middleware('auth')->prefix('admin')->as('admin.')->group(function () {
    Route::controller(App\Http\Controllers\Admin\PageController::class)->group(function () {
        Route::get('/', 'index')->name('dashboard');
    });
    Route::resource('lending', App\Http\Controllers\Admin\LendingController::class);
    Route::resource('guest', App\Http\Controllers\Admin\GuestController::class);
    Route::resource('items', App\Http\Controllers\Admin\ItemsController::class);

    Route::controller(App\Http\Controllers\ExportController::class)->group(function () {
        Route::get('/export/datatamu', 'exportDataTamu')->name('export.datatamu');
        Route::get('/export/datapeminjaman', 'exportDataPeminjaman')->name('export.peminjaman');
    });
});

app/Models/Guest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Guest extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/GuestController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Guest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class GuestController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        return \view('admin.guest.index', [
            'guests' => Guest::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
        $guest = Guest::find($id);

        $guest->destroy($id);

        if (!\is_null($guest->ss_akun_siapkerja)) {
            Storage::disk('public')->delete('ss_akun_kerja/' . $guest->ss_akun_siapkerja);
        }

        return redirect()->route('admin.guest.index')->with('success', 'Data Berhasil Dihapus');
    }
}

resources/views/admin/guest/edit.blade.php
<div>
    <!-- The best way to take care of the future is to take care of the present moment. - Thich Nhat Hanh -->
</div>

resources/views/admin/guest/index.blade.php
@extends('layouts.admin')

@section('title', 'Daftar Tamu')

@section('content')
    <div class="card card-body shadow">
        <div class="row">
            <div class="col-lg">
                <h3 class="text-primary mb-3">Daftar Tamu</h3>
            </div>
            <div class="col-lg-2 text-end">
                <a href="{{ route('admin.export.datatamu') }}" target="_blank" rel="noopener noreferrer"
                    class="btn btn-sm btn-outline-info">
                    <em class="bi bi-filetype-xlsx me-2"></em> Export Data Tamu
                </a>
            </div>
        </div>
        @include('alerts')
        <div class="table-responsive">
            <table class="table table-striped table-hovered" id="table">
                <thead>
                    <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Nama</th>
                        <th scope="col">Punya Akun SIAPkerja</th>
                        <th scope="col">Domisili</th>
                        <th scope="col">Alumni BBPVP</th>
                        <th scope="col">Tanggal Daftar</th>
                        <th scope="col">Opsi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($guests as $b)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $b->nama }}</td>
                            <td>{{ $b->punya_akun }}</td>
                            <td>{{ $b->domisili }}</td>
                            <td>
                                {{ $b->alumni_bbpvp }}
                            </td>
                            <td>{{ $b->created_at }}</td>
                            <td class="d-flex">
                                <form action="{{ route('admin.guest.destroy', ['guest' => $b->id]) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-outline-danger">
                                        <em class="bi bi-trash"></em>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/admin/guest/show.blade.php
<div>
    <!-- The biggest battle is the war against ignorance. - Mustafa Kemal Atatürk -->
</div>