routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::controller(App\Http\Controllers\PagesController::class)
    ->as('page.')
    ->group(function () {
        Route::get('/', 'index')->name('home');
        Route::get('/about', 'about')->name('about');
        Route::get('/contact', 'contact')->name('contact');
        Route::get('/ulasan/{jenisUlasan}', 'ulasan')->name('ulasan');
        Route::post('/ulasan/{jenisUlasan}', 'ulasanPost')->name('ulasan.post');
    });

Route::controller(App\Http\Controllers\MenuController::class)
    ->as('menu.')
    ->prefix('menu')
    ->group(function () {
        Route::get('/', 'menu')->name('menu');
        Route::get('/pengunjung', 'pengunjung')->name('pengunjung');
        Route::get('/forms/pengunjung', 'pengunjung')->name('forms.pengunjung');
        Route::get('/peminjaman', 'peminjaman')->name('peminjaman');
    });


Route::controller(App\Http\Controllers\Service\AuthController::class)->prefix('auth')->group(function () {
    Route::get('login', 'loginPage')->middleware('guest')->name('login');
    Route::post('login', 'loginPost')->middleware('guest')->name('login.post');
    Route::post('logout', 'logout')->middleware('auth')->name('logout');
});
Route::middleware('auth')->prefix('admin')->as('admin.')->group(function () {
    Route::controller(App\Http\Controllers\Admin\PageController::class)->group(function () {
        Route::get('/', 'index')->name('dashboard');
    });
    Route::resource('lending', App\Http\Controllers\Admin\LendingController::class);
    Route::resource('guest', App\Http\Controllers\Admin\GuestController::class);
    Route::resource('items', App\Http\Controllers\Admin\ItemsController::class);

    Route::controller(App\Http\Controllers\ExportController::class)->group(function () {
        Route::get('/export/datatamu', 'exportDataTamu')->name('export.datatamu');
        Route::get('/export/datapeminjaman', 'exportDataPeminjaman')->name('export.peminjaman');
    });
});

resources/views/pages/about.blade.php
@extends('layouts.frontpage')

@section('title', 'Tentang BBPVP')


@section('content')
    @include('components.navbar-frontpage')
    <section class="row align-items-center mt-3">
        <div class="col-lg">
            <img src="{{ asset('svg/about-image.svg') }}" alt="SIAPkerjaImg">
        </div>
        <div class="col-lg">
            <h1 class="text-center mb-3">Tentang BBPVP Bandung</h1>
            <p class="mb-3 text-justify">Balai Besar Pelatihan Vokasi Dan Produktivitas (BBPVP) Bandung Adalah
                Lembaga Pelatihan Pemerintah Yang Merupakan Salah Satu Unit
                Pelaksana Teknis Pusat (UPTP) Dibawah Direktorat Jenderal Pembinaan
                Pelatihan Dan Produktivitas, Kementerian Ketenagakerjaan Republik
                Indonesia, Berdasarkan Peraturan Menteri Ketenagakerjaan Republik
                Indonesia Nomor 21 Tahun 2015. BBPLK Bandung Memiliki Tugas
                Melaksanakan Pengembanganpelatihan, Pemberdayaan, Dan Sertifikasi
                Tenaga Kerja, Instruktur, Dan Tenaga Pelatihan. BBPLK Diresmikan
                Pada 23 Februari 1952 Atas Inisiatif Pemerintah Republik Indonesia
                Bekerjasama Dengan Program Colombo Plan. BBPLK Terletak Di J
                alan Jenderal Gatot Subroto No. 170, Bandung, Dengan Luas Lahan
                Sekitar 3 Hektar.</p>
        </div>
    </section>

@endsection

resources/views/pages/contact.blade.php
@extends('layouts.frontpage')

@section('title', 'Kontak BBPVP')


@section('content')
    @include('components.navbar-frontpage')
    <h1 class="mb-3">Contact</h1>
    <section class="row align-items-center">
        <div class="col-lg">
            <div class="d-flex mb-3">
                <img src="{{ asset('svg/geoloc.svg') }}" alt="Geoloc" style="width: 50px;">
                <div class="ms-4">
                    <legend class="fw-bold">Alamat Kantor</legend>
                    <p class="mb-3 text-justify">JL. JENDERAL GATOT SUBROTO NO. 170 KELURAHAN GUMURUH KECAMATAN BATUNUNGGAL
                        KOTA BANDUNG</p>
                </div>
            </div>
            <div class="d-flex mb-3">
                <img src="{{ asset('svg/email.svg') }}" alt="Email" style="width: 50px;">
                <div class="ms-4">
                    <legend class="fw-bold">Email</legend>
                    <p class="mb-3 text-justify">
                        <a href="mailto:bbpvp.bandung@kemnaker.go.id"
                            class="text-white text-decoration-none">bbpvp.bandung@kemnaker.go.id</a>
                    </p>
                </div>
            </div>
            <div class="d-flex mb-3">
                <img src="{{ asset('svg/phone.svg') }}" alt="Phone" style="width: 50px;">
                <div class="ms-4">
                    <legend class="fw-bold">Call:</legend>
                    <p class="mb-3 text-justify">022-7312564</p>
                </div>
            </div>
        </div>
        <div class="col-lg">
            <img src="{{ asset('svg/contact-image.svg') }}" alt="SIAPkerjaImg">
        </div>
    </section>

@endsection

resources/views/pages/home.blade.php
@extends('layouts.frontpage')

@section('title', 'Selamat Datang Di BBPVP Bandung Oleh Kementrian Ketenagakerjaan')


@section('content')
    @include('components.navbar-frontpage')
    <section class="row align-items-center mt-3">
        <div class="col-lg">
            <h1 class="mb-3">Selamat Datang Di BBPVP Bandung Oleh Kementrian Ketenagakerjaan</h1>
            <p class="mb-4">Tingkatkan Kompetensimu dengan mengikuti Pelatihan PBK Kejuruan Otomotif, Manufaktur,
                Refrigerasi, TIK dan
                Metodologi.</p>
            <a href="{{ route('menu.menu') }}" class="btn btn-light rounded-pill px-4">
                Get Started
            </a>
        </div>
        <div class="col-lg text-end">
            <img src="{{ asset('svg/home-image.svg') }}" alt="SIAPkerjaImg">
        </div>
    </section>

@endsection

resources/views/pages/ulasan.blade.php
@extends('layouts.frontpage')
@section('title', 'Ulasan Layanan')

@push('styles')
    <style>
        .rate {
            float: left;
            height: 56px;
            padding: 0 10px;
        }

        .rate:not(:checked)>input {
            position: absolute;
            top: -9999px;
        }

        .rate:not(:checked)>label {
            float: right;
            width: 1em;
            overflow: hidden;
            white-space: nowrap;
            cursor: pointer;
            font-size: 45px;
            color: #ccc;
        }

        .rate:not(:checked)>label:before {
            content: '★ ';
        }

        .rate>input:checked~label {
            color: #ffc700;
        }

        .rate:not(:checked)>label:hover,
        .rate:not(:checked)>label:hover~label {
            color: #deb217;
        }

        .rate>input:checked+label:hover,
        .rate>input:checked+label:hover~label,
        .rate>input:checked~label:hover,
        .rate>input:checked~label:hover~label,
        .rate>label:hover~input:checked~label {
            color: #c59b08;
        }

        /* Modified from: https://github.com/mukulkant/Star-rating-using-pure-css */
    </style>
@endpush


@section('content')
    <section class="d-flex justify-content-center flex-column">
        <form action="{{ route('page.ulasan.post', ['jenisUlasan' => $jenisUlasan]) }}" method="post">
            @csrf
            <div class="mb-3 d-flex flex-column justify-content-center align-items-center text-center">
                <legend>Kualitas Layanan</legend>
                <div class="rate" style="width: 250px">
                    <input type="radio" id="star5" name="rate" value="5" />
                    <label for="star5" title="text">5 stars</label>
                    <input type="radio" id="star4" name="rate" value="4" />
                    <label for="star4" title="text">4 stars</label>
                    <input type="radio" id="star3" name="rate" value="3" />
                    <label for="star3" title="text">3 stars</label>
                    <input type="radio" id="star2" name="rate" value="2" />
                    <label for="star2" title="text">2 stars</label>
                    <input type="radio" id="star1" name="rate" value="1" />
                    <label for="star1" title="text">1 star</label>
                </div>
            </div>
            <div class="mb-3 d-flex flex-column justify-content-center align-items-center text-center">
                <legend>Saran dan Kritik</legend>
                <textarea name="desc" id="desc" rows="3" class="form-control" placeholder="Berikan Ulasan Anda"></textarea>
            </div>
            <div class="mb-3  text-center">
                <a href="{{ route('page.home') }}" class="btn btn-light">
                    Kembali ke Beranda
                </a>
                <button type="submit" class="btn btn-primary me-1">
                    Simpan Ulasan
                </button>
            </div>
        </form>
    </section>
@endsection